#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Corso.Bologna.Navite.Droid.Resource", IsApplication=true)]

namespace Corso.Bologna.Navite.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int DetailsView_ImageView = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int DetailsView_IngredientsListView = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int DetailsView_NameView = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int Image_SimpleRecipeCell = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int MainView_ListView = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int MainView_WelcomeText = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int Name_SimpleRecipeCell = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DeatailsView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainView_RecipeList_SimpleRecipeCell = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int button = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
